// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oraxbvhlrujcjxcvfbqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yYXhidmhscnVqY2p4Y3ZmYnF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMjEyMTEsImV4cCI6MjA2ODY5NzIxMX0.u2uQEG8QvOmT5RvekLDZPqFIDLssPKLSnVknjvuzrzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});