// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykoomposnwecdfeeooij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlrb29tcG9zbndlY2RmZWVvb2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTAxMjcsImV4cCI6MjA2ODc2NjEyN30.KueRd8_OgVFKzmRkARQZc26pzl-GUt7rAsvias52-Fg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});